/mini_alpha/explore_camera_remote_node:
  ros__parameters:
    # --- Subscription Settings ---
    # The compressed image topic to subscribe to for processing.
    subscribe_topic: "/mini_alpha/exploreHD/image/compressed"

    video:
      product_name: 'exploreHD'
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
    # --- Auxiliary Processing ---
    # Enable/disable different processing pipelines.
    aux_process:
      img_raw: False
      img_raw_framerate: 10
      img_calibrated: True
      img_calibrated_framerate: 15

    # --- AprilTag Detection Settings ---
    apriltag:
      enable: True
      family: 'tag25h9'
      size: 0.21
      publish_rate: 10
      detector:
        nthreads: 2
        quad_decimate: 1.0
        quad_sigma: 0.0
        refine_edges: True
        decode_sharpening: 0.25

    # Camera calibration
    camera:
      intrinsics:
        fx: 312.318105
        fy: 312.305770
        cx: 340.379411
        cy: 187.766393
      distortion: [-0.065969, -0.017838, 0.013425, -0.002813]
      fisheye: True
      undistort_crop: True

    # --- General Settings ---
    # ROS frame_id to use for published topics. Should match the source frame_id.
    ros:
      frame_id: "dwe_camera_frame"

    # JPEG quality for any newly compressed topics (e.g., calibrated, apriltag).
    compression:
      jpeg_quality: 90
