# explore camera
/mini_alpha/explore_camera_node:
  ros__parameters:
    ### Video stream settings ###
    video:
      product_name: 'exploreHD'
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
    ### Settings for the low-bandwidth compressed stream ###
    # (0 target_fps will disable this topic)
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    ### Camera controls and calibrations ###
    camera:
      # hardware control
      # --- Exposure Controls (Manual) ---
      auto_exposure: True                # MUST be False for manual control.
      exposure_time: 156                  # TUNE THIS VALUE: Manually set for correct brightness.
      gain: 0                             # Minimum digital gain to reduce noise.
      # --- White Balance Controls (Manual) ---
      white_balance_automatic: True      # MUST be False for manual control.
      white_balance_temperature: 4600     # TUNE THIS VALUE: Manually set for correct color.
      # --- Enhancement & Compensation Filters (Disabled/Minimal) ---
      sharpness: 0                        # Minimum sharpness (disables edge enhancement).
      backlight_compensation: 0           # Minimum (disabled).
      power_line_frequency: 0             # Disabled. May cause flicker under AC lights.
      # --- Color & Tone Controls (Neutral/Default) ---
      brightness: 0                       # Neutral brightness.
      contrast: 32                        # Lower contrast for a "flatter" image.
      saturation: 64                      # Neutral color saturation.
      hue: 0                              # Neutral hue.
      gamma: 100                          # Default gamma curve.
    ### ROS related ###
    ros:
      frame_id: "explore_camera_frame" # Unique TF frame_id

# usbpcb camera
/mini_alpha/usbpcb_camera_node:
  ros__parameters:
    ### Video stream settings ###
    video:
      product_name: 'H264'
      width: 640
      height: 360
      framerate: 15
      format: 'MJPG'
    ### Settings for the low-bandwidth compressed stream ###
    # (0 target_fps will disable this topic)
    compression:
      width: 320
      height: 240
      target_fps: 0
      jpeg_quality: 75
    ### Camera controls and calibrations ###
    camera:
      # hardware control
      # --- Exposure Controls (Manual) ---
      auto_exposure: True                # MUST be False for manual control.
      exposure_time: 156                  # TUNE THIS VALUE: Manually set for correct brightness.
      gain: 0                             # Minimum digital gain to reduce noise.
      # --- White Balance Controls (Manual) ---
      white_balance_automatic: True      # MUST be False for manual control.
      white_balance_temperature: 4600     # TUNE THIS VALUE: Manually set for correct color.
      # --- Enhancement & Compensation Filters (Disabled/Minimal) ---
      sharpness: 0                        # Minimum sharpness (disables edge enhancement).
      backlight_compensation: 0           # Minimum (disabled).
      power_line_frequency: 0             # Disabled. May cause flicker under AC lights.
      # --- Color & Tone Controls (Neutral/Default) ---
      brightness: 0                       # Neutral brightness.
      contrast: 32                        # Lower contrast for a "flatter" image.
      saturation: 64                      # Neutral color saturation.
      hue: 0                              # Neutral hue.
      gamma: 100                          # Default gamma curve.
    ### ROS related ###
    ros:
      frame_id: "usbpcb_camera_frame" # Unique TF frame_id
